// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqmgvgsnjkqceyorzlrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxbWd2Z3NuamtxY2V5b3J6bHJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzMDQ0MTEsImV4cCI6MjA3NTg4MDQxMX0.9EMQ8nP8UvIbx7E96oL_BKALXnpaysLcvTU4l3JByn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});